name: flutter_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Service Lacotar 
  get_it: ^7.2.0

  # State Management
  flutter_bloc: ^8.1.1

  # Equality
  equatable: ^2.0.5

  # Functional Programming
  dartz: ^0.10.1

  # Remote API
  connectivity_plus: ^3.0.2
  http: ^0.13.5

  # Local Cache
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Mocks  
  mockito: ^5.3.2

flutter:
  uses-material-design: true